# Generated by Django 6.0.5 on 2026-05-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0023_epgsource_programme_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epgsource',
            name='api_key',
        ),
        migrations.AddField(
            model_name='epgsource',
            name='password',
            field=models.CharField(blank=True, help_text='Password for credential-based EPG sources (e.g. Schedules Direct)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='epgsource',
            name='username',
            field=models.CharField(blank=True, help_text='Username for credential-based EPG sources (e.g. Schedules Direct)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programdata',
            name='program_id',
            field=models.CharField(blank=True, help_text='Schedules Direct programID (e.g. EP123456789). Null for XMLTV sources.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='epgsource',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Custom properties for source-specific configuration', null=True),
        ),
        migrations.CreateModel(
            name='SDProgramMD5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(help_text='Schedules Direct programID (e.g. EP123456789)', max_length=64)),
                ('md5', models.CharField(help_text='MD5 hash of the program metadata from Schedules Direct', max_length=22)),
                ('epg_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd_program_md5s', to='epg.epgsource')),
            ],
            options={
                'unique_together': {('epg_source', 'program_id')},
            },
        ),
        migrations.CreateModel(
            name='SDScheduleMD5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='Schedules Direct stationID', max_length=20)),
                ('date', models.DateField(help_text='Schedule date (UTC)')),
                ('md5', models.CharField(help_text='MD5 hash of the schedule for this station/date from Schedules Direct', max_length=22)),
                ('last_modified', models.DateTimeField(help_text='Last modified timestamp from Schedules Direct')),
                ('epg_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd_schedule_md5s', to='epg.epgsource')),
            ],
            options={
                'indexes': [models.Index(fields=['epg_source', 'station_id'], name='epg_sdsched_epg_sou_0d700e_idx')],
                'unique_together': {('epg_source', 'station_id', 'date')},
            },
        ),
    ]
